modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
A lightweight Jade addon for MineColonies.

Track the growth of MineColonies crops directly in your tooltip:
• Growth percentage
• Mature crop detection
• Vanilla-style Jade integration

Designed to feel like a natural extension of Jade itself.

Fast. Simple. Clean.
'''
logoFile="icon.png"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jade"
type="optional"
versionRange="[15.10.5,)"
ordering="AFTER"
side="CLIENT"